### ISSUE TITLE
Skeleton navlink broken

### ISSUE THREAD

**Issue by jemus42** [hrbrmstr/markdowntemplates#6]
There seems to be some accidental HTML escaping in the navlink code.

Example result:

![](http://dump.jemu.name/PdVM7.png)

HTML source of affected area:

```
<div class="hdr u-max-full-width"><a href="&lt;a href=" http: stats.jemu.name qm" class="uri">http://stats.jemu.name/qm</a>&quot;&gt;QM Aufgaben</a></div>
```

YAML used:

```

---
title: "Title"
author: "Jemus42"
navtitle: "QM Aufgaben"
navlink: "http://stats.jemu.name/qm"
date: "`r Sys.Date()`"
output: markdowntemplates::skeleton

---
```

Version:
`markdowntemplates   0.3.2.9000 2016-02-06 Github (hrbrmstr/markdowntemplates@33b2ed5)`

**Comment by hrbrmstr** [comment]
thx. I'll see what machinations are involved in dealing with the escaping

**Comment by hrbrmstr** [comment]
I took the easy way out (apologies :-). Links are now specified in a single YAML element using markdown link syntax.

**Comment by jemus42** [comment]
Naughty!

I can live with that though, thanks :)
